spring:
  application:
    name: webshell
info.app.name: @project.artifactId@
info.app.version: @project.version@
spring.devtools.restart.enabled: true
spring.devtools.livereload.enabled: true

server:
  port: 8080

