spring:
  application:
    name: adaptor-poller
info.app.name: @project.artifactId@
info.app.version: @project.version@
# Enable automatic restart (default is true)
spring.devtools.restart.enabled: true

# Exclude static resources (optional)
#spring.devtools.restart.exclude: static/**,public/**

# Enable live reload for HTML changes (Requires browser plugin)
spring.devtools.livereload.enabled: true


#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/intact-ats-database
#spring.datasource.username: root
#spring.datasource.password: root

server:
  port: 8080
# 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

spring.elasticsearch.uris: http://localhost:9200
